namespace Quotes.BusinessLayer.Modal
{
    public class QuoteModel
    {
        public int QuoteID { get; set; }
        public Guid QuoteGUID { get; set; }
        public Guid? OriginalQuoteGUID { get; set; }
        public Guid? RenewalOfQuoteGuid { get; set; }
        public string ControlNo { get; set; }
        public Guid ControlGuid { get; set; }
        public string EndorsementNum { get; set; }
        public DateTime? EndorsementEffective { get; set; }
        public string EndorsementComment { get; set; }
        public string EndorsementCalculationType { get; set; }
        public int? QuoteStatusReasonID { get; set; }
        public string QuoteStatusComment { get; set; }
        public int? TransactionTypeID { get; set; }
        public Guid? SubmissionGroupGuid { get; set; }
        public Guid? QuotingLocationGuid { get; set; }
        public Guid? IssuingLocationGuid { get; set; }
        public Guid? CompanyLocationGuid { get; set; }
        public Guid? LineGUID { get; set; }
        public string StateID { get; set; }
        public Guid? ProducerContactGuid { get; set; }
        public Guid? UnderwriterUserGuid { get; set; }
        public Guid? RetailerGuid { get; set; }
        public int? QuoteStatusID { get; set; }
        public DateTime EffectiveDate { get; set; }
        public DateTime ExpirationDate { get; set; }
        public int? PolicyTypeID { get; set; }
        public DateTime DateCreated { get; set; }
        public Guid? TACSRUserGuid { get; set; }
        public string PolicyNumber { get; set; }
        public int? PolicyNumberIndex { get; set; }
        public string SIC_Code { get; set; }
        public int? BillingTypeID { get; set; }
        public decimal? MinimumEarnedPercentage { get; set; }
        public DateTime? DateIssued { get; set; }
        public Guid? IssuedByUserID { get; set; }
        public DateTime? DateBound { get; set; }
        public Guid? BoundByUserID { get; set; }
        public string InsuredDBA { get; set; }
        public string InsuredFEIN { get; set; }
        public string InsuredSSN { get; set; }
        public int? InsuredBusinessTypeID { get; set; }
        public string InsuredPolicyName { get; set; }
        public string InsuredCorporationName { get; set; }
        public string InsuredSalutation { get; set; }
        public string InsuredFirstName { get; set; }
        public string InsuredMiddleName { get; set; }
        public string InsuredLastName { get; set; }
        public string InsuredAddress1 { get; set; }
        public string InsuredAddress2 { get; set; }
        public string InsuredCity { get; set; }
        public string InsuredCounty { get; set; }
        public string InsuredState { get; set; }
        public string InsuredISOCountryCode { get; set; }
        public string InsuredRegion { get; set; }
        public string InsuredZipCode { get; set; }
        public string InsuredZipPlus { get; set; }
        public string InsuredPhone { get; set; }
        public string InsuredFax { get; set; }
        public string ProducerName { get; set; }
        public string ProducerLocationName { get; set; }
        public string ProducerAddress1 { get; set; }
        public string ProducerAddress2 { get; set; }
        public string ProducerCity { get; set; }
        public string ProducerCounty { get; set; }
        public string ProducerState { get; set; }
        public string ProducerISOCountryCode { get; set; }
        public string ProducerRegion { get; set; }
        public string ProducerZipCode { get; set; }
        public string ProducerZipPlus { get; set; }
        public string ProducerPhone { get; set; }
        public string ProducerFax { get; set; }
        public Guid? FinanceCompanyGuid { get; set; }
        public Guid? CompanyLineGuid { get; set; }
        public string AccountNumber { get; set; }
        public int? CostCenterID { get; set; }
        public int? InspectionCompanyID { get; set; }
        public bool? QuickQuote { get; set; }
        public int? InstallmentBillingQuoteOptionID { get; set; }
        public string InsuredAddress1_Billing { get; set; }
        public string InsuredAddress2_Billing { get; set; }
        public string InsuredCity_Billing { get; set; }
        public string InsuredCounty_Billing { get; set; }
        public string InsuredState_Billing { get; set; }
        public string InsuredISOCountryCode_Billing { get; set; }
        public string InsuredRegion_Billing { get; set; }
        public string InsuredZipCode_Billing { get; set; }
        public string InsuredZipPlus_Billing { get; set; }
        public string InsuredPhone_Billing { get; set; }
        public string InsuredFax_Billing { get; set; }
        public int? NOCTypeID { get; set; }
        public string ProducerAddress1_Billing { get; set; }
        public string ProducerAddress2_Billing { get; set; }
        public string ProducerCity_Billing { get; set; }
        public string ProducerCounty_Billing { get; set; }
        public string ProducerState_Billing { get; set; }
        public string ProducerISOCountryCode_Billing { get; set; }
        public string ProducerRegion_Billing { get; set; }
        public string ProducerZipCode_Billing { get; set; }
        public string ProducerZipPlus_Billing { get; set; }
        public string ProducerPhone_Billing { get; set; }
        public string ProducerFax_Billing { get; set; }
        public bool? PolicyFormsAutoApplied { get; set; }
        public decimal? PreviousPremium { get; set; }
        public decimal? TargetPremium { get; set; }
        public int? NetRate_QuoteID { get; set; }
        public string NetRateXML { get; set; }
        public string ExpiringPolicyNumber { get; set; }
        public string RiskDescription { get; set; }
        public Guid? UnderwritingAssistantGuid { get; set; }
        public int? ProducerLocationID { get; set; }
        public int? PolicyNumberRuleID { get; set; }
        public Guid? SecProducerContactGuid { get; set; }
        public string StrippedPolicyNumber { get; set; }
        public string StrippedInsuredPolicyName { get; set; }
        public Guid? RewriteOfQuoteGuid { get; set; }
        public DateTime? EndtRequestDate { get; set; }
        public string FinanceCompanyAccountNumber { get; set; }
        public string StrippedInsuredDBA { get; set; }
        public int? EarnedPremiumTypeID { get; set; }
        public bool? Auditable { get; set; }
        public string RenewalOfControlNum { get; set; }
        public string InsuredMobileNumber { get; set; }
        public string NAICSCode { get; set; }
        public string StripInsuredCorporationName { get; set; }
        public string DisplayStatus { get; set; }
        public decimal? ProducerCompositeCommission { get; set; }
        public decimal? CompanyCompositeCommission { get; set; }
    }
}
        
    
