//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", ConfigurationName="LoginService.LogonSoap")]
    public interface LogonSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.LoginReturn> LoginAsync(string programCode, string contactType, string email, string password, string projectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/GenerateToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.LoginReturn> GenerateTokenAsync(LoginService.UserLogin Credentials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/ExtendToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.ExtendTokenResponse> ExtendTokenAsync(LoginService.ExtendTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/RefreshToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.RefreshTokenResponse> RefreshTokenAsync(LoginService.RefreshTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.GetUserInfoResponse> GetUserInfoAsync(LoginService.GetUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/UserGuidFromLoginToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.UserGuidFromLoginTokenResponse> UserGuidFromLoginTokenAsync(LoginService.UserGuidFromLoginTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/LoginIMSUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.LoginReturn> LoginIMSUserAsync(string userName, string tripleDESEncryptedPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/LoginUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Guid> LoginUserAsync(string userName, string tripleDESEncryptedPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/GetEntityDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.GetEntityDetailsResponse> GetEntityDetailsAsync(LoginService.GetEntityDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/GetTokenPermissions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.GetTokenPermissionsResponse> GetTokenPermissionsAsync(LoginService.GetTokenPermissionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/GetEntityPermissions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<LoginService.GetEntityPermissionsResponse> GetEntityPermissionsAsync(LoginService.GetEntityPermissionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMSWebServices/Logon/HealthCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> HealthCheckAsync();
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginReturnExt))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
    public partial class LoginReturn
    {
        
        private System.Guid userGuidField;
        
        private System.Guid tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid UserGuid
        {
            get
            {
                return this.userGuidField;
            }
            set
            {
                this.userGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
    public partial class TokenHeader
    {
        
        private System.Guid tokenField;
        
        private string contextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactLogin))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
    public partial class UserLogin
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
    public partial class ContactLogin : UserLogin
    {
        
        private string programCodeField;
        
        private string contactTypeField;
        
        private string projectNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProgramCode
        {
            get
            {
                return this.programCodeField;
            }
            set
            {
                this.programCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ContactType
        {
            get
            {
                return this.contactTypeField;
            }
            set
            {
                this.contactTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProjectName
        {
            get
            {
                return this.projectNameField;
            }
            set
            {
                this.projectNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
    public partial class LoginReturnExt : LoginReturn
    {
        
        private string ipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IP
        {
            get
            {
                return this.ipField;
            }
            set
            {
                this.ipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExtendToken", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class ExtendTokenRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
        public LoginService.TokenHeader TokenHeader;
        
        public ExtendTokenRequest()
        {
        }
        
        public ExtendTokenRequest(LoginService.TokenHeader TokenHeader)
        {
            this.TokenHeader = TokenHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExtendTokenResponse", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class ExtendTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public bool ExtendTokenResult;
        
        public ExtendTokenResponse()
        {
        }
        
        public ExtendTokenResponse(bool ExtendTokenResult)
        {
            this.ExtendTokenResult = ExtendTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefreshToken", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class RefreshTokenRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
        public LoginService.TokenHeader TokenHeader;
        
        public RefreshTokenRequest()
        {
        }
        
        public RefreshTokenRequest(LoginService.TokenHeader TokenHeader)
        {
            this.TokenHeader = TokenHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RefreshTokenResponse", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class RefreshTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public LoginService.LoginReturn RefreshTokenResult;
        
        public RefreshTokenResponse()
        {
        }
        
        public RefreshTokenResponse(LoginService.LoginReturn RefreshTokenResult)
        {
            this.RefreshTokenResult = RefreshTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfo", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class GetUserInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
        public LoginService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=1)]
        public string password;
        
        public GetUserInfoRequest()
        {
        }
        
        public GetUserInfoRequest(LoginService.TokenHeader TokenHeader, string username, string password)
        {
            this.TokenHeader = TokenHeader;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInfoResponse", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class GetUserInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public System.Guid GetUserInfoResult;
        
        public GetUserInfoResponse()
        {
        }
        
        public GetUserInfoResponse(System.Guid GetUserInfoResult)
        {
            this.GetUserInfoResult = GetUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGuidFromLoginToken", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class UserGuidFromLoginTokenRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
        public LoginService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public System.Guid token;
        
        public UserGuidFromLoginTokenRequest()
        {
        }
        
        public UserGuidFromLoginTokenRequest(LoginService.TokenHeader TokenHeader, System.Guid token)
        {
            this.TokenHeader = TokenHeader;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UserGuidFromLoginTokenResponse", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class UserGuidFromLoginTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public System.Guid UserGuidFromLoginTokenResult;
        
        public UserGuidFromLoginTokenResponse()
        {
        }
        
        public UserGuidFromLoginTokenResponse(System.Guid UserGuidFromLoginTokenResult)
        {
            this.UserGuidFromLoginTokenResult = UserGuidFromLoginTokenResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/IMSWebServices/Logon")]
    public partial class GetEntityDetailsResponseGetEntityDetailsResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntityDetails", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class GetEntityDetailsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
        public LoginService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public System.Guid entityGuid;
        
        public GetEntityDetailsRequest()
        {
        }
        
        public GetEntityDetailsRequest(LoginService.TokenHeader TokenHeader, System.Guid entityGuid)
        {
            this.TokenHeader = TokenHeader;
            this.entityGuid = entityGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntityDetailsResponse", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class GetEntityDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public LoginService.GetEntityDetailsResponseGetEntityDetailsResult GetEntityDetailsResult;
        
        public GetEntityDetailsResponse()
        {
        }
        
        public GetEntityDetailsResponse(LoginService.GetEntityDetailsResponseGetEntityDetailsResult GetEntityDetailsResult)
        {
            this.GetEntityDetailsResult = GetEntityDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenPermissions", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class GetTokenPermissionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
        public LoginService.TokenHeader TokenHeader;
        
        public GetTokenPermissionsRequest()
        {
        }
        
        public GetTokenPermissionsRequest(LoginService.TokenHeader TokenHeader)
        {
            this.TokenHeader = TokenHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTokenPermissionsResponse", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class GetTokenPermissionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public string[] GetTokenPermissionsResult;
        
        public GetTokenPermissionsResponse()
        {
        }
        
        public GetTokenPermissionsResponse(string[] GetTokenPermissionsResult)
        {
            this.GetTokenPermissionsResult = GetTokenPermissionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntityPermissions", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class GetEntityPermissionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon")]
        public LoginService.TokenHeader TokenHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> EntityGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=1)]
        public string ProgramCode;
        
        public GetEntityPermissionsRequest()
        {
        }
        
        public GetEntityPermissionsRequest(LoginService.TokenHeader TokenHeader, System.Nullable<System.Guid> EntityGuid, string ProgramCode)
        {
            this.TokenHeader = TokenHeader;
            this.EntityGuid = EntityGuid;
            this.ProgramCode = ProgramCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEntityPermissionsResponse", WrapperNamespace="http://tempuri.org/IMSWebServices/Logon", IsWrapped=true)]
    public partial class GetEntityPermissionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/IMSWebServices/Logon", Order=0)]
        public string[] GetEntityPermissionsResult;
        
        public GetEntityPermissionsResponse()
        {
        }
        
        public GetEntityPermissionsResponse(string[] GetEntityPermissionsResult)
        {
            this.GetEntityPermissionsResult = GetEntityPermissionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface LogonSoapChannel : LoginService.LogonSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class LogonSoapClient : System.ServiceModel.ClientBase<LoginService.LogonSoap>, LoginService.LogonSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LogonSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LogonSoapClient.GetBindingForEndpoint(endpointConfiguration), LogonSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LogonSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LogonSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LogonSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LogonSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LogonSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LoginService.LoginReturn> LoginAsync(string programCode, string contactType, string email, string password, string projectName)
        {
            return base.Channel.LoginAsync(programCode, contactType, email, password, projectName);
        }
        
        public System.Threading.Tasks.Task<LoginService.LoginReturn> GenerateTokenAsync(LoginService.UserLogin Credentials)
        {
            return base.Channel.GenerateTokenAsync(Credentials);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginService.ExtendTokenResponse> LoginService.LogonSoap.ExtendTokenAsync(LoginService.ExtendTokenRequest request)
        {
            return base.Channel.ExtendTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginService.ExtendTokenResponse> ExtendTokenAsync(LoginService.TokenHeader TokenHeader)
        {
            LoginService.ExtendTokenRequest inValue = new LoginService.ExtendTokenRequest();
            inValue.TokenHeader = TokenHeader;
            return ((LoginService.LogonSoap)(this)).ExtendTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginService.RefreshTokenResponse> LoginService.LogonSoap.RefreshTokenAsync(LoginService.RefreshTokenRequest request)
        {
            return base.Channel.RefreshTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginService.RefreshTokenResponse> RefreshTokenAsync(LoginService.TokenHeader TokenHeader)
        {
            LoginService.RefreshTokenRequest inValue = new LoginService.RefreshTokenRequest();
            inValue.TokenHeader = TokenHeader;
            return ((LoginService.LogonSoap)(this)).RefreshTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginService.GetUserInfoResponse> LoginService.LogonSoap.GetUserInfoAsync(LoginService.GetUserInfoRequest request)
        {
            return base.Channel.GetUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginService.GetUserInfoResponse> GetUserInfoAsync(LoginService.TokenHeader TokenHeader, string username, string password)
        {
            LoginService.GetUserInfoRequest inValue = new LoginService.GetUserInfoRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.username = username;
            inValue.password = password;
            return ((LoginService.LogonSoap)(this)).GetUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginService.UserGuidFromLoginTokenResponse> LoginService.LogonSoap.UserGuidFromLoginTokenAsync(LoginService.UserGuidFromLoginTokenRequest request)
        {
            return base.Channel.UserGuidFromLoginTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginService.UserGuidFromLoginTokenResponse> UserGuidFromLoginTokenAsync(LoginService.TokenHeader TokenHeader, System.Guid token)
        {
            LoginService.UserGuidFromLoginTokenRequest inValue = new LoginService.UserGuidFromLoginTokenRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.token = token;
            return ((LoginService.LogonSoap)(this)).UserGuidFromLoginTokenAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<LoginService.LoginReturn> LoginIMSUserAsync(string userName, string tripleDESEncryptedPassword)
        {
            return base.Channel.LoginIMSUserAsync(userName, tripleDESEncryptedPassword);
        }
        
        public System.Threading.Tasks.Task<System.Guid> LoginUserAsync(string userName, string tripleDESEncryptedPassword)
        {
            return base.Channel.LoginUserAsync(userName, tripleDESEncryptedPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginService.GetEntityDetailsResponse> LoginService.LogonSoap.GetEntityDetailsAsync(LoginService.GetEntityDetailsRequest request)
        {
            return base.Channel.GetEntityDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginService.GetEntityDetailsResponse> GetEntityDetailsAsync(LoginService.TokenHeader TokenHeader, System.Guid entityGuid)
        {
            LoginService.GetEntityDetailsRequest inValue = new LoginService.GetEntityDetailsRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.entityGuid = entityGuid;
            return ((LoginService.LogonSoap)(this)).GetEntityDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginService.GetTokenPermissionsResponse> LoginService.LogonSoap.GetTokenPermissionsAsync(LoginService.GetTokenPermissionsRequest request)
        {
            return base.Channel.GetTokenPermissionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginService.GetTokenPermissionsResponse> GetTokenPermissionsAsync(LoginService.TokenHeader TokenHeader)
        {
            LoginService.GetTokenPermissionsRequest inValue = new LoginService.GetTokenPermissionsRequest();
            inValue.TokenHeader = TokenHeader;
            return ((LoginService.LogonSoap)(this)).GetTokenPermissionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoginService.GetEntityPermissionsResponse> LoginService.LogonSoap.GetEntityPermissionsAsync(LoginService.GetEntityPermissionsRequest request)
        {
            return base.Channel.GetEntityPermissionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoginService.GetEntityPermissionsResponse> GetEntityPermissionsAsync(LoginService.TokenHeader TokenHeader, System.Nullable<System.Guid> EntityGuid, string ProgramCode)
        {
            LoginService.GetEntityPermissionsRequest inValue = new LoginService.GetEntityPermissionsRequest();
            inValue.TokenHeader = TokenHeader;
            inValue.EntityGuid = EntityGuid;
            inValue.ProgramCode = ProgramCode;
            return ((LoginService.LogonSoap)(this)).GetEntityPermissionsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> HealthCheckAsync()
        {
            return base.Channel.HealthCheckAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LogonSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LogonSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LogonSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ws2.mgasystems.com/ims_kmg_dev/logon.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LogonSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ws2.mgasystems.com/ims_kmg_dev/logon.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LogonSoap,
            
            LogonSoap12,
        }
    }
}
